
# config/packages/lexik_jwt_authentication.yaml
lexik_jwt_authentication:
    # En producción usará el contenido directo de las variables de entorno
    # En desarrollo local necesitarás sobrescribir esto en .env.local
    secret_key: '%env(JWT_SECRET_KEY)%'
    public_key: '%env(JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600