nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://127.0.0.7:5500']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/':
      allow_origin: ['http://127.0.0.7:5500']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['GET', 'POST', 'OPTIONS']
      allow_credentials: true
