nelmio_cors:
  defaults:
    allow_origin: ["*"] # Puedes cambiar '*' por los dominios permitidos (p.ej., 'http://localhost:3000')
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type", "Authorization"]
    max_age: 3600
    allow_credentials: true
  paths:
    "^/api/": # Ajusta la ruta según tu API
      allow_origin: ["*"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      allow_headers: ["Content-Type", "Authorization"]
      max_age: 3600
      allow_credentials: true
