# config/packages/nelmio_cors.yaml
nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["*"] # Puedes definir orígenes específicos, por ejemplo: ['http://example.com']
    allow_headers: ["Content-Type", "Authorization", "X-Requested-With"]
    expose_headers: []
    max_age: 3600
    allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  paths:
    "^/api/": # Especifica las rutas donde quieres habilitar CORS (por ejemplo, solo para el API)
      allow_origin: ["*"] # O especifica dominios, como 'http://example.com'
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
